// frontend/src/components/NodePalette.tsx
import React from 'react'
import { NodeKind } from '@/types/workflow'

interface NodeType {
  type: NodeKind
  label: string
  description: string
  icon: string
  color: string
}

const nodeTypes: NodeType[] = [
  {
    type: 'trigger',
    label: 'Trigger',
    description: 'Start workflow execution',
    icon: '⚡',
    color: '#10B981'
  },
  {
    type: 'action',
    label: 'Action',
    description: 'Perform an action',
    icon: '⚙️',
    color: '#3B82F6'
  },
  {
    type: 'condition',
    label: 'Condition',
    description: 'Make decisions',
    icon: '❓',
    color: '#F59E0B'
  },
  {
    type: 'transformer',
    label: 'Transformer',
    description: 'Transform data',
    icon: '🔄',
    color: '#8B5CF6'
  },
  {
    type: 'webhook',
    label: 'Webhook',
    description: 'External trigger',
    icon: '🌐',
    color: '#EF4444'
  }
]

export const NodePalette: React.FC = () => {
  const onDragStart = (event: React.DragEvent, nodeType: NodeKind) => {
    event.dataTransfer.setData('application/reactflow', nodeType)
    event.dataTransfer.effectAllowed = 'move'
  }

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-4 shadow-lg">
      <h3 className="text-lg font-semibold text-gray-800 mb-4">Node Types</h3>
      
      <div className="space-y-2">
        {nodeTypes.map((nodeType) => (
          <div
            key={nodeType.type}
            className="flex items-center gap-3 p-3 border border-gray-200 rounded-lg hover:bg-gray-50 cursor-grab active:cursor-grabbing transition-colors"
            draggable
            onDragStart={(event) => onDragStart(event, nodeType.type)}
          >
            <div
              className="w-8 h-8 rounded-full flex items-center justify-center text-white text-lg"
              style={{ backgroundColor: nodeType.color }}
            >
              {nodeType.icon}
            </div>
            
            <div className="flex-1">
              <div className="font-medium text-gray-800">
                {nodeType.label}
              </div>
              <div className="text-sm text-gray-500">
                {nodeType.description}
              </div>
            </div>
          </div>
        ))}
      </div>
      
      <div className="mt-4 text-xs text-gray-500 text-center">
        Drag nodes to the canvas to create connections
      </div>
    </div>
  )
}

// frontend/src/components/NodePalette.vue
<template>
  <div class="bg-white border-r border-gray-200 p-4">
    <h3 class="text-lg font-semibold text-gray-900 mb-4">Node Palette</h3>
    
    <div class="space-y-2">
      <div class="text-sm font-medium text-gray-700 mb-2">Triggers</div>
      <div
        v-for="node in triggerNodes"
        :key="node.type"
        class="p-3 border border-gray-200 rounded-lg cursor-move hover:bg-gray-50 transition-colors"
        draggable="true"
        @dragstart="onDragStart($event, node)"
      >
        <div class="flex items-center space-x-2">
          <div class="w-3 h-3 rounded-full bg-green-500"></div>
          <span class="text-sm font-medium">{{ node.label }}</span>
        </div>
        <p class="text-xs text-gray-500 mt-1">{{ node.description }}</p>
      </div>

      <div class="text-sm font-medium text-gray-700 mb-2 mt-4">Actions</div>
      <div
        v-for="node in actionNodes"
        :key="node.type"
        class="p-3 border border-gray-200 rounded-lg cursor-move hover:bg-gray-50 transition-colors"
        draggable="true"
        @dragstart="onDragStart($event, node)"
      >
        <div class="flex items-center space-x-2">
          <div class="w-3 h-3 rounded-full bg-blue-500"></div>
          <span class="text-sm font-medium">{{ node.label }}</span>
        </div>
        <p class="text-xs text-gray-500 mt-1">{{ node.description }}</p>
      </div>

      <div class="text-sm font-medium text-gray-700 mb-2 mt-4">Logic</div>
      <div
        v-for="node in logicNodes"
        :key="node.type"
        class="p-3 border border-gray-200 rounded-lg cursor-move hover:bg-gray-50 transition-colors"
        draggable="true"
        @dragstart="onDragStart($event, node)"
      >
        <div class="flex items-center space-x-2">
          <div class="w-3 h-3 rounded-full bg-purple-500"></div>
          <span class="text-sm font-medium">{{ node.label }}</span>
        </div>
        <p class="text-xs text-gray-500 mt-1">{{ node.description }}</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const triggerNodes = ref([
  {
    type: 'gmail_trigger',
    label: 'Gmail Trigger',
    description: 'Trigger on new email'
  },
  {
    type: 'webhook_trigger',
    label: 'Webhook',
    description: 'Trigger on HTTP request'
  },
  {
    type: 'schedule_trigger',
    label: 'Schedule',
    description: 'Trigger on schedule'
  }
])

const actionNodes = ref([
  {
    type: 'gmail_action',
    label: 'Send Email',
    description: 'Send email via Gmail'
  },
  {
    type: 'slack_action',
    label: 'Slack Message',
    description: 'Send Slack message'
  },
  {
    type: 'sheets_action',
    label: 'Google Sheets',
    description: 'Update spreadsheet'
  },
  {
    type: 'http_request',
    label: 'HTTP Request',
    description: 'Make HTTP request'
  }
])

const logicNodes = ref([
  {
    type: 'condition',
    label: 'Condition',
    description: 'If/else logic'
  },
  {
    type: 'transformer',
    label: 'Data Transformer',
    description: 'Transform data'
  },
  {
    type: 'filter',
    label: 'Filter',
    description: 'Filter data'
  }
])

const onDragStart = (event, node) => {
  event.dataTransfer.setData('application/json', JSON.stringify(node))
  event.dataTransfer.effectAllowed = 'copy'
}
</script>
